
alias i3conf='vim ~/.config/i3/config'
alias polyconf='ranger ~/.config/polybar/'
alias piconf='vim ~/.config/picom/picom.conf'
alias ri3='i3-msg reload ; i3-msg restart'
alias logoff='sudo pkill -u $USER'
alias alaconf='vim ~/.config/alacritty/alacritty.toml'
alias twow='wine $HOME/turtle/VanillaFixes.exe'
alias zconf='vim ~/.zshrc'
alias sozsh='source ~/.zshrc'
alias notes='ranger $HOME/buhfur.github.io/notes'
alias todo='vim $HOME/buhfur.github.io/todo/todo.md -p $HOME/buhfur.github.io/todo/wowtodo.md '
alias updg='sudo apt -y update && sudo apt -y upgrade'
alias roficonf='ranger ~/.config/rofi'
alias rls='sudo systemctl daemon-reload'
alias sys='sudo systemctl'
alias gp='git add . ; git commit -a ; git push'
alias gdock='docker run -it -v /var/run/docker.sock:/var/run/docker.sock kakshipth/gomanagedocker:latest'
alias jf='cd /mnt/media/jellyfin/'
# SSH aliases
alias proxmox='ssh root@proxmox'
alias jellyfin='ssh jellyfin@jellyfin'
alias tserver='ssh torrent-user@torrent-server'
alias dnsserver='ssh dns-user@dns-server'

